name: Deploy documentation 

on:
  push:
    branches:
      - pages

jobs:
  deploy_github_pages:
    runs-on: ubuntu-20.04

    steps:    
    - name: Deploy Javascript Docs to Github Pages
      run: |
        mkdir public
        cd bindings/wasm
        npm install
        npm run docs
        mv ./docs ../../public/jsdocs
